[package]
name = "document"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
shared-kernel = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
