[package]
name = "object-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
bytes = "1"
aws-sdk-s3 = "1"
aws-smithy-types = "1"
shared-kernel = { workspace = true }
futures-util = { workspace = true }
tokio-util = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
http = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tempfile = "3"

[lints]
workspace = true
