[package]
name = "migration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "migration"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
runtime-config = { workspace = true }
runtime-migration = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }

[lints]
workspace = true
