[package]
name = "ai-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
runtime-config = { workspace = true }
observability = { workspace = true }
document-processing = { path = "../../crates/document-processing" }
document-processing-postgres = { path = "../../crates/document-processing-postgres" }
document-processing-sqlite = { path = "../../crates/document-processing-sqlite" }
document-postgres = { workspace = true }
document = { workspace = true }
object-storage = { workspace = true }
sqlx = { workspace = true }

[lints]
workspace = true
