[package]
name = "project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
shared-kernel = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
