[package]
name = "shared-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.architecture]
bounded_context = "shared-kernel"
layer = "shared-kernel"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
